name: todolist
description: "A to-do-list app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  get_it: ^7.2.0
  injectable: ^2.4.2
  json_annotation: ^4.3.0
  path_provider: ^2.0.11
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.1.5
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.1
  
flutter:
  uses-material-design: true
